# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-04 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Attrib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mirror',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('last_heartbeat', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Repo',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('filesystem_dir', models.CharField(max_length=50, unique=True)),
                ('manager_type', models.CharField(choices=[('apt', 'APT'), ('yum', 'YUM'), ('json', 'JSON'), ('docker', 'Docker'), ('pypi', 'PyPi')], max_length=6)),
                ('show_only_latest', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('distroversion_list', models.ManyToManyField(to='Attrib.DistroVersion')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Attrib.Tag')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='mirror',
            name='repo_list',
            field=models.ManyToManyField(to='Repo.Repo'),
        ),
    ]
