# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-04 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistroVersion',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('distro', models.CharField(choices=[('debian', 'Debian'), ('rhel', 'RHEL'), ('sles', 'SLES'), ('none', 'None')], max_length=6)),
                ('version', models.CharField(blank=True, max_length=10, null=True)),
                ('file_type', models.CharField(max_length=20)),
                ('release_names', models.CharField(blank=True, help_text='tab delimited list of things like el5, trusty, something that is in filename that tells what version it belongs to', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('change_control_required', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('required_list', models.ManyToManyField(related_name='_tag_required_list_+', to='Attrib.Tag', symmetrical=False)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AlterUniqueTogether(
            name='distroversion',
            unique_together=set([('distro', 'version', 'file_type')]),
        ),
    ]
