# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-01-04 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Attrib', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('deprocated_count', models.IntegerField(default=20)),
                ('failed_count', models.IntegerField(default=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackageFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(editable=False, max_length=50)),
                ('type', models.CharField(choices=[('deb', 'deb'), ('rpm', 'RPM'), ('rsc', 'Resource'), ('ova', 'OVA'), ('docker', 'Docker'), ('python', 'Python')], editable=False, max_length=6)),
                ('arch', models.CharField(choices=[('x86_64', 'x86_64'), ('i386', 'i386'), ('arm64', 'ARM64'), ('all', 'All')], editable=False, max_length=6)),
                ('justification', models.TextField()),
                ('provenance', models.TextField()),
                ('file', models.FileField(editable=False, upload_to='')),
                ('sha256', models.CharField(editable=False, max_length=64)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_by', models.CharField(blank=True, max_length=40, null=True)),
                ('deprocated_at', models.DateTimeField(blank=True, null=True)),
                ('deprocated_by', models.CharField(blank=True, max_length=40, null=True)),
                ('created_by', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('distroversion', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='Attrib.DistroVersion')),
                ('package', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Package.Package')),
            ],
            options={
                'permissions': (('can_tag', 'Can add Tag'), ('can_untag', 'Can remove a Tag'), ('can_fail', 'Can Mark a Package File as Failed'), ('can_unfail', 'Can Un-Mark a Package File as Failed'), ('can_deprocate', 'Can Mark a Package File as Deprocated'), ('can_undeprocate', 'Can Un-Mark a Package File as Deprocated')),
                'default_permissions': ('add',),
            },
        ),
        migrations.CreateModel(
            name='PackageFileTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('by', models.CharField(max_length=40)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('change_control_id', models.CharField(blank=True, max_length=50, null=True)),
                ('package_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Package.PackageFile')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Attrib.Tag')),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='packagefile',
            name='tag_list',
            field=models.ManyToManyField(through='Package.PackageFileTag', to='Attrib.Tag'),
        ),
        migrations.AlterUniqueTogether(
            name='packagefiletag',
            unique_together=set([('package_file', 'tag')]),
        ),
        migrations.AlterUniqueTogether(
            name='packagefile',
            unique_together=set([('package', 'distroversion', 'version', 'type', 'arch')]),
        ),
    ]
