#!/usr/bin/python -u
import os

os.environ.setdefault( "DJANGO_SETTINGS_MODULE", "packrat.settings" )

from packrat.Repos.models import PackageFile

good_list = [ i[0][2:] for i in PackageFile.objects.all().values_list( 'file' ) ] # take off the ./


for file in os.listdir( FILEPATH ):
  if file not in good_list:
    print 'Removing "%s"...' % file
    #os.unlink( file )
