#!/usr/bin/python3
import os

os.environ.setdefault( "DJANGO_SETTINGS_MODULE", "packrat.settings" )

import django
django.setup()

from django.conf import settings
from packrat.Repos.models import PackageFile

good_list = [ i[0][2:] for i in PackageFile.objects.all().values_list( 'file' ) ]  # take off the ./

for filename in os.listdir( settings.MEDIA_ROOT ):
  if filename not in good_list:
    print( 'Removing "{0}"...'.format( filename ) )
    os.unlink( os.path.join( settings.MEDIA_ROOT, filename ) )
